####################
### 这个是启动本服务的配置文件，其它的application-xxx.properties 是开发者的个性化配置，不用关心。
### 你可以在 https://txlcn.org/zh-cn/docs/setting/manager.html 看到所有的个性化配置
###################
#logging:
#  level:
#    com:
#      codingapi: debug
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    use-generated-keys: true
#server:
#  port: 7970
#spring:
#  application:
#    name: tx-manager
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tx-manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    type: com.zaxxer.hikari.HikariDataSource
#    password: 721000
#    username: root
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#
#  redis: #redis 主机
#    host: 127.0.0.1
#    port: 6379 #redis 端口
#tx-lcn:
#  logger:
#    enabled: true # 开启日志
#  manager:
#    concurrent-level: 128
#    dtx-time: 30000 # 分布式事务执行总时间
#    heart-time: 15000 # 心跳检测时间(ms)
#    host: 127.0.0.1 # TxManager Host Ip
#    port: 8070 # TxClient连接请求端口
