spring:
  application:
    name: spring-cloud-eureka

server:
  port: 80

eureka:
  instance:
    hostname: spring-cloud-eureka-80 #eureka服务端的实例名称
  client:
    eviction-interval-timer-in-ms: 5000 # 每隔5秒钟，进行一次服务列表的清理
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/   #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。